### ISSUE TITLE
Can you add support for generics in the return results?

### ISSUE THREAD

**Issue by ayanjoyful** [TongchengOpenSource/smart-doc#1]

**Comment by shalousun** [comment]
Smart-doc inherently supports generic returns. To use generics, you need to specify the exact type. If it doesn't support the scenario you're using, please provide the specific return interface and return model so that we can quickly locate and fix the related issues.
smart-doc天生支持泛型返回，使用泛型需要指定具体类型，如果实在不支持你使用的场景，请提供下具体的返回接口和返回模型，以便快速定位修复相关问题

**Comment by ayanjoyful** [comment]
Thank you for your prompt reply. Perhaps my testing method was incorrect yesterday. After testing today, I found that it is indeed supported. Thank you!
感谢您百忙之中回复,可能我昨天测试方法不对,今天测试了一下,发现是支持的.谢谢!
