### ISSUE TITLE
Generate Postman request parameters.

### ISSUE THREAD

**Issue by ciweigg2** [TongchengOpenSource/smart-doc#16]
For POST method interfaces, generating request parameters is complete. However, why aren't request parameters generated for GET methods? This results in having to fill them in manually every time. Can support for generating request parameters for GET methods be added? When importing into Postman, can it intelligently merge instead of forcefully overwriting? It's possible that the required request parameters have been set.
对post方式的接口生成请求参数完整
但是对get方式为什么不生成请求参数了 导致每次都需要自己填
可以支持下get方式的请求参数生成么
导入postman能否智能合并 别强行覆盖了 可能设置过需要的请求参数了

**Comment by netdied** [comment]
1. The generation of GET parameters requires configuring the server URL.
2. Currently, we do not support generating request parameters for GET methods that retrieve form data.
If this is not the issue, could you provide a sample?
As for intelligent merging, it's impossible because the import process is handled by Postman, and you can only choose to overwrite or create a new one.
1.get参数的生成需要配置serverurl 
2..暂不支持get获取表单数据生成请求参数
如果不是上面的问题 可以提供一下样例么？
 智能合并没办法  导入是postman做的事 只能选择是覆盖还是创建一个新的

**Comment by ciweigg2** [comment]
![F5C4791B-FF5D-40F9-B807-05242D3845CE](https://user-images.githubusercontent.com/41536971/70989482-af1e4500-20fe-11ea-9150-1e44261afbee.jpeg)
Can such GET request parameters be generated?
这样的get请求参数能生成么？

**Comment by netdied** [comment]
Add the @RequestParam annotation.
添加@RequestParam注解
