### ISSUE TITLE
Enumeration support is not good.

### ISSUE THREAD

**Issue by victory-wu** [TongchengOpenSource/smart-doc#21]
**URL:** http://192.168.31.100:9011/a/customer/info/audit/{action}
**Type:** POST

**Content-Type:** application/json; charset=utf-8

**Description:** 

**Request-headers:**

Parameter | Type | Description | Required | Since
-- | -- | -- | -- | --
action | string | No comments found. | true | -
id | int64 | 主键ID | false | -
comment | string | No comments found. | false | -
action | string | No comments found. | false | -

The action here is an enumeration type, but it is displayed as a string, which confuses the users.
我这里的action是一个枚举类型，但是生成出来显示为string，让使用者摸不着头脑。

**Comment by netdied** [comment]
For front-end transmission, an enumeration is just a string.
枚举对于前端传值就是个string啊

**Comment by victory-wu** [comment]
If it's a string type, the other party can send any value.
If it's an enumeration type, they can only choose values from the listed options.
For example, if I have an enumeration that requires the other party to only send 'Male' or 'Female', but they don't know the meaning of my naming and send 'male' or 'women' instead, then I would need to call the developer into a meeting to discuss it.
I really like this excellent documentation generation tool.
It would be great if it could clearly define the range of values, as it would reduce the number of times we need to communicate.
如果是string类型，对方可以随意传值。
如果是枚举类型，只能在列出出来的值以内选择值。
比如我枚举，要求对方只能传，男，女；而对方不知道我命名的含义，传输一个male, women，
这样我就得需要把开发者叫到会议室里面沟通一次
对于这样优秀的文档生成工具，我非常喜欢
如果能明确出值的范围，那可就太好了，能够减少我们沟通的次数。

**Comment by netdied** [comment]
Okay, we will consider this.
Currently, you can use the @apiNote annotation to explain it.
好的 这个我们会考虑的
目前你可以通过@apinote注解说明一下

**Comment by nnzbz** [comment]
I'd like to add that enumeration types are almost essential in all API interfaces. Only with this feature fully implemented can it be truly practical.
By the way, most company standards for enumerations involve custom definitions, inheriting from a certain interface, and overriding the constructor, such as:
https://gitee.com/sunyurepository/smart-doc/wikis/%E5%AF%BC%E5%87%BA%E6%95%B0%E6%8D%AE%E5%AD%97%E5%85%B8?sort_id=1713399
I hope you can take this into consideration to automatically achieve this effect.
我补充一下，枚举类型几乎是所有API接口必用的，完成了这个功能才能真正实用
BTW，大多数公司规范中的枚举是自定义的，继承某个接口，并重写构造，如：
https://gitee.com/sunyurepository/smart-doc/wikis/%E5%AF%BC%E5%87%BA%E6%95%B0%E6%8D%AE%E5%AD%97%E5%85%B8?sort_id=1713399
希望能考虑进去，自动达到这个效果

**Comment by netdied** [comment]
![image](https://user-images.githubusercontent.com/20217389/84795301-e1671b80-b029-11ea-86c1-68c7c51d1f7b.png)
No worries, I've been too busy before... Could you check if this is the effect you're looking for?
不好意思 之前太忙了。。你看看是不是这个效果

**Comment by shixianqing** [comment]
枚举类优化的问题，是不是还没发到新一个版本

**Comment by shixianqing** [comment]
The problem should be as follows:

1. The backend defines the following interface
public ApiResult findUserBySex(@RequestParam SexEnum sexEnum){}

2. The content of the SexEnum enumeration is shown in the figure below.

![image](https://user-images.githubusercontent.com/43101321/85222364-e858aa00-b3ec-11ea-832e-d68ae44f7254.png)

3. The document should be displayed on the front end as:
   
![image](https://user-images.githubusercontent.com/43101321/85222531-6c5f6180-b3ee-11ea-8827-3937bcbe5802.png)

**When the backend receives parameters with an enumeration class, the front end can only send 'MALE' or 'FEMALE', not the code values, otherwise the backend cannot deserialize it into a SexEnum object.**

4. When an enumeration class is used as a member variable of a JavaBean:
![image](https://user-images.githubusercontent.com/43101321/85222433-83518400-b3ed-11ea-8a65-e773af96702d.png)
When userVo is used as a request parameter for the interface, the documentation page display is also incorrect.
![image](https://user-images.githubusercontent.com/43101321/85222455-ac721480-b3ed-11ea-979f-4deeb03a4634.png)
I think it should be displayed like this:
![image](https://user-images.githubusercontent.com/43101321/85222505-286c5c80-b3ee-11ea-968a-190cb8742e73.png)

**Comment by shalousun** [comment]
@shixianqing Enumerations used as parameters for passing values to the front end are not necessarily 'MALE' or 'FEMALE'; some people convert them, and most databases store numbers.
