### ISSUE TITLE
Date type generates incorrect documentation.

### ISSUE THREAD

**Issue by QinHongZhe** [TongchengOpenSource/smart-doc#245]
## Your Environment (Your Using Environment)

* smart-doc version: 2.4.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.2
* build tool version(maven or gradle): maven

## Expected Behavior (Expected Result)

Correctly generate Data type
## Current Behavior (Current Result)

Generates String
![image](https://user-images.githubusercontent.com/25653313/164701423-60ed4472-8f02-49e8-9c6e-eaf6f1fcc07d.png)
![image](https://user-images.githubusercontent.com/25653313/164701461-4b7cb69f-6797-416a-a051-0db2331054cc.png)

## Steps to Reproduce (Steps to Produce the Bug)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@QinHongZhe This is not a bug. Don't always look at the problem from a Java language perspective. Smart-doc is designed with more consideration for being language-agnostic. Even the most direct frontend integration does not involve submitting date types. In JDK 8, there are many time types, and it's impossible to annotate them all according to Java types.
These data types have been fixed since the beginning of our open source project, and 99% of users have no questions about them.

**Comment by QinHongZhe** [comment]
Alright. That part also feels a bit inappropriate later on.

**Comment by QinHongZhe** [comment]
我close掉了
