### ISSUE TITLE
It seems that the multi-environment configuration is not taking effect.

### ISSUE THREAD

**Issue by youngledo** [TongchengOpenSource/smart-doc#278]
## Your Environment(Your Use Environment)

* smart-doc version: 2.4.6
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.6
* build tool version(maven or gradle): maven-3.8.1

## Expected Behavior(Expected Results)

Generate documentation for different environments.

## Current Behavior(Current Results)

According to the installation documentation: https://smart-doc-group.github.io/#/zh-cn/QA?id=smart-doc%e5%a6%82%e4%bd%95%e5%81%9a%e5%a4%9a%e7%8e%af%e5%a2%83%e9%85%8d%e7%bd%ae%ef%bc%9f

It is found that `smart-doc.json` must be configured to generate documentation. At the same time, after configuring `smart-doc-test.json` and setting the corresponding environment, the documentation for the corresponding environment is not generated.

## Possible Solution(Bug Resolution Suggestions)

It is suggested to define configurations and files according to the Spring Boot environment variables, while avoiding identical configurations (overwriting).

## Steps to Reproduce (Steps to Produce the Bug, Please Provide Code Examples if Possible)

1. Simply define smart-doc.json and smart-doc-test.json respectively to reproduce.

**Comment by shalousun** [comment]
@youngledo The official documentation merely provides a conceptual framework for you to expand upon and find solutions. The essence of the issue is not related to smart-doc; the plugin allows you to specify `./src/main/resources/smart-doc.json`, and clearly, this filename is not hardcoded. The problem for users to solve is how to dynamically pass the desired filename to the `configFile` configuration option. Evidently, Maven profiles can achieve this, and for those using CI tools, another approach could be to use a script to replace the filename, offering multiple paths to the same outcome. It depends on how flexibly you handle it. As for why it cannot adopt the same pattern as Spring, it's because smart-doc only exists during the compilation phase, not at runtime; its working principles differ, inevitably leading to some variations in outcomes.

**Comment by youngledo** [comment]
Okay, I understand.
