### ISSUE TITLE
The parameters of the form-based request include a nested pagination object, which results in incorrect concatenation of the request URL parameters.

### ISSUE THREAD

**Issue by liangfj** [TongchengOpenSource/smart-doc#286]
## Your Environment(您的使用环境)
smart-doc-maven-plugin:2.4.1

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
![image](https://user-images.githubusercontent.com/41361831/172788342-2074d47f-fbe8-4c0a-a35a-57817c497477.png)
2.
![image](https://user-images.githubusercontent.com/41361831/172788414-d658b9eb-9de9-4805-921c-57af8c59fbfe.png)
3.
![image](https://user-images.githubusercontent.com/41361831/172788712-c80be9bd-6d70-439d-8849-ff723aaad918.png)
4.
![image](https://user-images.githubusercontent.com/41361831/172788994-473e9097-8e3f-451f-a348-d77cb87c7e73.png)
5. The URL for sending the request
Using the parameters mentioned above, the request is sent with incorrectly concatenated URL parameters:
http://192.168.2.162:9301/iotmanage/iotProduct/list?page=&%E2%94%94%E2%94%80pageNum=1&%E2%94%94%E2%94%80pageSize=10&%E2%94%94%E2%94%80orderBy=id%20desc

It should be correctly concatenated as follows:
http://192.168.2.162:9301/iotmanage/iotProduct/list?page.pageNum=1&page.pageSize=10

**Comment by shalousun** [comment]
@liangfj Please upgrade to the latest version yourself and report any issues after testing. The official team will not track or address any issues with historical versions. Also, please note that aside from file uploads, try to use JSON requests as much as possible. Nested forms will not be supported in later versions. Smart-doc has always been a tool that focuses more on guiding users to follow current mainstream best programming practices, rather than trying to meet everyone's needs.

**Comment by liangfj** [comment]
I have upgraded to 2.4.6 and generated the documentation, but encountered a null pointer exception.
![image](https://user-images.githubusercontent.com/41361831/173044813-7b33b6b1-6e66-4750-a1f2-e5781cd8d828.png)

Switching back to 2.4.5, I can generate the documentation, but the issue with parameter concatenation still exists.

**Comment by chenqi146** [comment]
Upgrade to version 2.4.7.
