### ISSUE TITLE
Grouping different controllers always results in the default grouping.

### ISSUE THREAD

**Issue by Fang-g** [TongchengOpenSource/smart-doc#326]
1. When not using the grouping feature, everything works perfectly normal.
2. When using grouping, the following issue always occurs at the beginning:
3. The framework always has common interfaces inherited from BaseController, but they have already been ignored using @Ignore.

![image](https://user-images.githubusercontent.com/55525460/184052955-4e71d54f-3967-464b-b6ba-c16e0707d4ab.png)

**Comment by shalousun** [comment]
@Fang-g Firstly, when submitting an issue, please fill it out according to the issue template format; otherwise, the officials will not be aware of your version usage. Following the issue template is already a consensus in the open-source industry, so please make sure to include the key version information.
Regarding grouping: The presence of a default group is not considered a bug because, after you enable grouping, controllers that do not match your configured grouping rules need to be categorized into a default group. Unless you find that the default group itself contains empty interfaces, and yet it still displays "default", only then would it be considered a bug.
Concerning the ineffectiveness of marking ignore, this may be due to an oversight in implementation.

**Comment by shalousun** [comment]
This issue has not been followed up, let's close it for now.
