### ISSUE TITLE
Pushed to torna, with an additional field `@since`

### ISSUE THREAD

**Issue by scofi** [TongchengOpenSource/smart-doc#362]
## Your Environment (您的使用环境)

* smart-doc version: 2.5.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version (maven or gradle): 3.8.2
* java version: 1.8
* sorna version: v1.17.0

## Expected Behavior (您期望的结果)

1. After importing sorna, remove the `@since` string from the request and response fields.
2. Could you provide a feature to upload documentation for a single controller only, currently all controller documents are uploaded.
3. Could there be an option to choose whether to update the documentation for a single interface? The information I changed on torna is overwritten when I upload again.

## Current Behavior (当前结果)

![image](https://user-images.githubusercontent.com/4952712/193234865-f6c60f18-a0b2-4d13-b412-438a216fc407.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. Click on the smart-doc torna:rest in the plugin.
2.
3.
4.

**Comment by shalousun** [comment]
1. "since" indicates since which version the field was added. This is just a bug; it gets pushed even if not specified.
2. Uploading a single controller can be automatically configured to a specific controller through packagefilter. As it supports regular expressions, you can make flexible modifications during the push.
3. If you wish to configure on torna to avoid overwrites, it is recommended to submit an issue to torna. Smart-doc does not have any operational interface, so you cannot selectively tick options.


Using smart-doc, the best practice is to ensure your code adheres to standards as much as possible. Utilizing tags like @mock allows for minimal manual intervention; the accuracy of the pushed code is high, and the definitions of interface types are clear. Another recommendation is to integrate it with CI (Continuous Integration) as much as possible. Delegating documentation generation to CI reduces the need for manual updates and uploads to torna. When time permits, testing can be performed through unit tests; if not, local HTML generation for debugging suffices. The more standardized the code and the more automated the process, the better the user experience. Otherwise, frequently changing configurations to generate documentation makes maintenance extremely difficult.

**Comment by shalousun** [comment]
The `@since` tag will be fixed in the next version.

**Comment by scofi** [comment]
> 1. "since" indicates since which version the field was added. This is just a bug; it gets pushed even if not specified.
> 2. Uploading a single controller can be automatically configured to a specific controller through packagefilter. As it supports regular expressions, you can make flexible modifications during the push.
> 3. If you wish to configure on torna to avoid overwrites, it is recommended to submit an issue to torna. Smart-doc does not have any operational interface, so you cannot selectively tick options.


Using smart-doc, the best practice is to ensure your code adheres to standards as much as possible. Utilizing tags like @mock allows for minimal manual intervention; the accuracy of the pushed code is high, and the definitions of interface types are clear. Another recommendation is to integrate it with CI (Continuous Integration) as much as possible. Delegating documentation generation to CI reduces the need for manual updates and uploads to torna. When time permits, testing can be performed through unit tests; if not, local HTML generation for debugging suffices. The more standardized the code and the more automated the process, the better the user experience. Otherwise, frequently changing configurations to generate documentation makes maintenance extremely difficult.



First and foremost, I greatly appreciate your suggestions. Regarding delegating documentation generation to CI, one issue is that the documentation must be prepared in advance because the front end relies on it, so I need to generate it before releasing the code.
