### ISSUE TITLE
After upgrading to the latest version, the left navigation bar cannot be expanded and only displays the primary directory. Additionally, clicking on a directory does not redirect to the specified location.

### ISSUE THREAD

**Issue by LFDwater** [TongchengOpenSource/smart-doc#382]
The current version is 2.6.2, which presents the aforementioned issues.
In version 2.4.4, only the issue of not displaying secondary directories was present; navigation still worked.
In version 2.2.4, none of the above issues were present.

**Comment by LFDwater** [comment]
![image](https://user-images.githubusercontent.com/38934315/200243110-dbe6ccc7-f081-4142-b529-7933b6a1b5c0.png)
Please provide the current configuration information.

**Comment by shalousun** [comment]
@LFDwater The inability to expand the left navigation bar is not a bug. Since version 2.2.5, support for grouping has been added, which now supports up to three levels of directories and does not support the default expanded view. It's not that it cannot be expanded; it can be done by clicking. As for the issue with higher versions not being able to navigate, you need to open the browser's console to check the specific errors reported by the front end and determine the cause. This issue is related to some formatting of comments and is not a common error. There have been no recent changes in the latest versions, and no one else has reported the same problem, including myself who is using the latest version in a project without any navigation issues. The main issue seems to be related to the data generated during use.

**Comment by LFDwater** [comment]
@shalousun Indeed, accessing .js on my side results in errors. I will look into it further, thank you for your response!!!

**Comment by LFDwater** [comment]
@shalousun I'm still not sure about the specific cause. Currently, it seems that an error occurs when loading highlight.min.js, while other static files load normally.
![image](https://user-images.githubusercontent.com/38934315/200641051-6863082b-472f-4d89-859e-6f869fa1f7b5.png)
The error message suggests that there's an issue whenever a match occurs.
![image](https://user-images.githubusercontent.com/38934315/200641331-54c006ec-dc72-416a-b922-27e304cd4fac.png)
![image](https://user-images.githubusercontent.com/38934315/200641483-e8ce5e3e-196d-409a-9987-95db43c8ead8.png)

Current Spring Boot version: 2.3.9.RELEASE, spring-boot-starter-thymeleaf: 2.7.5

**Comment by shalousun** [comment]
@shalousun I have not used spring-boot-starter-thymeleaf, so I suspect there might be a bug in it. In fact, you could directly open the HTML document in a browser to check; at least in my case, a Spring Boot project that does not use Thymeleaf does not have this issue.

**Comment by LFDwater** [comment]
> @shalousun I have not used spring-boot-starter-thymeleaf, so I suspect there might be a bug in it. In fact, you could directly open the HTML document in a browser to check; at least in my case, a Spring Boot project that does not use Thymeleaf does not have this issue.

The browser indeed has no issues. Then I'll try a different approach. Thanks!
