### ISSUE TITLE
In versions above 2.6.0, the generic resolution of return objects is incorrect.

### ISSUE THREAD

**Issue by nlClancy** [TongchengOpenSource/smart-doc#386]
## Your Environment(您的使用环境)

* smart-doc version:2.6.0+

## Expected Behavior(您期望的结果)
2.5.3 runtime results
![图片](https://user-images.githubusercontent.com/49982479/203246864-ad6b2cbb-9ae1-40d9-99ae-e087468ff88d.png)

## Current Behavior(当前结果)
Master runtime results
![图片](https://user-images.githubusercontent.com/49982479/203246839-ed0b1511-62df-4d9b-8fc2-6493ee75f611.png)

## Possible Solution(bug解决建议)

Occurring in version 2.6.0, the master can directly reproduce it.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
![图片](https://user-images.githubusercontent.com/49982479/203249297-2b2260f8-fdb2-4a03-92b5-ba8f02102f76.png)

**Comment by shalousun** [comment]
@nlClancy This is not a bug. As can be seen from your screenshot, all comments for the fields of CommonResult are missing, indicating that the source code could not be loaded. Without the source code, the field type becomes Object instead of the defined T. In older versions, a trick was used where the A in CommonResult was forcefully substituted for the Object type field. However, if the user has defined multiple generics or simply defined an Object type field, this forced substitution could lead to errors. The new version no longer supports such arbitrary logic; if the source code cannot be loaded, it will not proceed with processing. Therefore, ensure that the source code can be normally loaded when using it.

**Comment by nlClancy** [comment]
Thanks for the response, the issue has been resolved.
