### ISSUE TITLE
The return value of the parent interface is not recognized.

### ISSUE THREAD

**Issue by tank520** [TongchengOpenSource/smart-doc#444]
Environment:
SpringBoot：2.3.12.RELEASE
Smart-doc-maven-plugin: 2.6.3

Problem：
After the Controller inherits a BaseController (which contains common generic interfaces), the parameters can be recognized after generating the document, but the response parameters are empty.
Controller继承一个BaseController（里面有通用泛型接口），生成文档后，参数可以识别，响应参数为空。

**Comment by shalousun** [comment]
@tank520 Please provide the example code.

**Comment by tank520** [comment]
Example of interface in an abstract class: Translation into English
@PostMapping("page/list")
public CommonResult<PageResult<R>> list(@Valid @RequestBody Q dto) {
    .......
}

**Comment by shalousun** [comment]
@tank520 Test cases have been added at https://github.com/smart-doc-group/smart-doc-example-cn/blob/master/src/main/java/com/power/doc/controller/BaseController.java and https://github.com/smart-doc-group/smart-doc-example-cn/blob/master/src/main/java/com/power/doc/controller/ValidatorTestController.java . Currently, the issue cannot be reproduced, and the problem might stem from your failure to let smart-doc load the source code of the CommonResult class. Since Java does not have source code generics erasure, smart-doc cannot parse it. You can refer to the related issues in the official documentation's FAQ section.

**Comment by tank520** [comment]
It's probably not an issue of failing to scan. Overriding in subclasses can be recognized, but the ones in the parent class cannot be identified.
应该不是没有扫描到的问题，子类重写就可以识别，唯独父类中的就识别不到

**Comment by shalousun** [comment]
> It's probably not an issue of failing to scan. Overriding in subclasses can be recognized, but the ones in the parent class cannot be identified.
应该不是没有扫描到的问题，子类重写就可以识别，唯独父类中的就识别不到

You can fork the test project and add an example that can reproduce the issue you are experiencing so we can fix it. The code you provided above has been added, but the problem cannot be reproduced.
你可以fork测试项目添加一个可以跑出来复现你问题的例子我们来修复，上面你提供的代码我们添加了无法复现问题

**Comment by tank520** [comment]
The cause has been identified; it was due to the naming of generics in the abstract class (six generics). Changing them to conform to the standards resolved the issue.
发现原因了，抽象类里面的泛型命名问题导致的（6个泛型），改成规范里面的就可以了。
