### ISSUE TITLE
When the response data includes enumeration types from a third-party jar, the type of the corresponding field in the documentation is displayed as object.

### ISSUE THREAD

**Issue by easycoder666** [TongchengOpenSource/smart-doc#499]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.8
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-gradle-plugin
* build tool version(maven or gradle): gradle

## Expected Behavior(您期望的结果)
When the response data includes enumeration types from a third-party jar, the type of the corresponding field in the documentation should be displayed as enum.
响应数据包含第三方jar的枚举类型时，文档对应字段的type应该显示enum

## Current Behavior(当前结果)
Enumeration types from third-party jars are not recognized.
未识别第三方jar的枚举类型

![s](https://github.com/smart-doc-group/smart-doc/assets/1560218/94c3138b-5c71-4837-a3ac-2ab9347aa2ea)
![s2](https://github.com/smart-doc-group/smart-doc/assets/1560218/e2a133ca-140e-45d3-afcb-fcd84a48fdeb)
After reviewing the official documentation, I am uncertainAfter reviewing the official documentation, I am uncertain or if it is necessary to I am uncertain whether it is a bug or if it is necessary to import the source code of the third-party jar? Please reply, thank you.
看了官方文档，不确定是bug还是必须要引入第三方jar的源码？望回复，多谢

**Comment by shalousun** [comment]
This needs to be investigated.
这个需要排查下

**Comment by shalousun** [comment]
<img width="349" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/9592228/b29acdbd-fcb5-42d3-92ff-e7c07f5a291a">

<img width="984" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/9592228/e12339fc-75e4-4ed1-8501-c0948561ae3e">

As shown in the image above, we are unable to reproduce it. The enumeration you mentioned comes from an open-source library. If it is from an open-source library, please provide the dependency information of the open-source library. If not, you can debug it yourself to see where the problem lies.
如上面图，我们无法复现，你个枚举时来自开源的，如果开源库的可以提供下开源库的依赖信息，如果不是可以自己debug下看下是哪里问题。

**Comment by easycoder666** [comment]
YesNoStatus is an enumeration in our own generic jar, which inherits from an interface.
I tried publishing the jar with source code to Nexus, and then including it in this project works well.
YesNoStatus是一个我们自己的通用jar中的枚举，继承了一个接口
我试了把带源码的jar发布到nexus，然后在本项目中include进来就好使了
![111](https://github.com/smart-doc-group/smart-doc/assets/1560218/267ba0f9-98c1-45dc-bcae-558250c17118)
![222](https://github.com/smart-doc-group/smart-doc/assets/1560218/564bf408-df51-42c4-90e3-5847bb973cce)
![333](https://github.com/smart-doc-group/smart-doc/assets/1560218/f19274eb-19aa-4f24-9353-33ad5cf682be)
