### ISSUE TITLE
In the HTML report, only the first directory in the left list displays a second-level directory.

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#51]
## Summary
In the HTML report, only the first directory in the left list displays a second-level directory. After reviewing the allinone.css file, it seems that by default, the second-level directories are set to not be displayed (`display: none`).

Suggestions:

1. It would be ideal if the left list could have a feature for collapsing and expanding directories. This way, users can choose when to display the second-level directories and when to hide them.
2. If implementing a collapsible feature is difficult, consider changing the default CSS for `sectorlevel2` to `display: block`, so that all second-level directories are visible by default. Alternatively, provide an option for users to decide whether to expand all directories or not.

**Comment by shalousun** [comment]
@zrlw The first-level directory being expanded is intentionally set by us to be open. This is because, when modifying the template, we aimed for consistency and simplicity. The directory font is not very prominent, so by default, we have it expanded to make it clear to regular users that the directory can be expanded and collapsed.
It's even less likely that everything will be expanded. Initially, it was all expanded, but we've gathered feedback that the vast majority of users do not want everything expanded. That's why the document is presented in its current form.
一级目录第一个展开是我们故意设置展开的。因为在修改这个模板的时候是为了模板的一致性和简洁性，目录字体不明显，默认展开是让普通使用者很明显的知道目录可以展开和折叠。
全部展开更不可能，一开始是全展开的，但是我们收集到绝大多数用户都不想全部展开。所以这就是当前文档呈现的样子。

**Comment by zrlw** [comment]
The intranet browser can't expand it (unable to access the external jquery.js), so the expansion function is not available when opening the generated HTML in an intranet environment.
内网浏览器展开不了（无法访问外网的jquery.js)，所以在内网环境打开生成的html没有展开功能了。
