### ISSUE TITLE
Control layer group validation: @Validated(Save.class) doesn't adapt correctly in the model. Issue #243 still exists in 2.6.8.

### ISSUE THREAD

**Issue by kezhiyang** [TongchengOpenSource/smart-doc#517]
When generating openapi, the @Validated(Save.class) group doesn't work.
生成openapi的时候 @Validated(Save.class) 分组不起作用。

**Comment by kezhiyang** [comment]
测试结果：分组类必须是内部类才行，不能外部定义Save.class类

**Comment by kezhiyang** [comment]
Downgrading to version 2.4.5 is usable.
回退到版本2.4.5可以使用

**Comment by kezhiyang** [comment]
Issues are present in versions 2.5.3, 2.6.0, and 2.7.0 as well.

**Comment by shalousun** [comment]
@kezhiyang If you can fix it, feel free to submit a PR (Pull Request) to contribute.

**Comment by kezhiyang** [comment]
@shalousun  I haven't looked at the source code, so I can't make the changes.

**Comment by shalousun** [comment]
@kezhiyang Could you please fork the https://github.com/smart-doc-group/smart-doc-example-cn project and add a sample that reproduces your issue to https://github.com/smart-doc-group/smart-doc-example-cn/blob/master/src/main/java/com/power/doc/controller/ValidatorTestController.java? We'll fix it later.

**Comment by netdied** [comment]
After upgrading to version 2.4.5, the generation of components changed, with the key value being the class name instead of a random string.
This has caused issues where only one component can be generated for the same entity class, and among group validations for the same entity class, only one required parameter takes effect, leading to failed group validations.
It is suggested to define different XxxxReq for different interfaces. Although there will be some redundancy, the code will be clearer.
