### ISSUE TITLE
Support for multiple-level interface inheritance in RPC.

### ISSUE THREAD

**Issue by UN010** [TongchengOpenSource/smart-doc#753]
## Summary(关于这个pr的描述)
Based on the results from using the plugin to parse, it only handled the first level of inheritance.
从使用插件解析结果看，只处理了第一层的继承关系

### Basic example(pr的用例)
There are three interfaces, each in a separate project. Interface A extends B, and B extends C. Both B and C have one method each. Currently, when parsing the results of the A interface, only the method from B is obtained; the method from C is not retrieved.
有三个接口，分别在三个项目中，A继承B，B继承C；其中B，C各有一个接口；目前A接口解析结果只有B中的方法，C中的方法并未获取

### Motivation(提出这个pr目的)
In some projects I've encountered, to consider business reuse, the inheritance hierarchy is defined over many layers. Currently, the parsing results in such scenarios are inaccurate. I hope there can be support for this scenario or if it's already implemented, I would like to know how I should configure it.
我遇到的有些项目为考虑业务复用，把继承关系定义很多层，目前这种场景下的解析结果不准确，希望可以支持这个场景或者已实现我应该怎么配置。

**Comment by linwumingshi** [comment]
@UN010 Below is a demo I wrote based on your issues. I configured scanning interface A and generated the API documentation that includes all interfaces.

下面是我根据你的问题写的一个demo。 我配置了扫描接口A，我生成的接口文档包含了所有接口。
![030919501922_0A](https://github.com/TongchengOpenSource/smart-doc/assets/25889679/e3f3930a-0634-4898-9343-044c6f76ed20)

The following is the Markdown API documentation generated using smart-doc, and there is no issue with inaccurate parsing results as you mentioned. If I misunderstood, please describe your question again.
以下是使用smart-doc生成的Markdown接口文档，并没有你说的解析结果不准确，如果是我的理解错误，请再次描述您的问题



# Test Project

| Version | Update Time | Status | Author | Description |
|---------|-------------|--------|--------|-------------|
|v2024-03-09 19:58:46|2024-03-09 19:58:46|auto|@test|Created by smart-doc|



## MyControllerA extends MyControllerB
### a
**URL:** http://127.0.0.1:3333/c/a

**Type:** GET

**Author:** test

**Content-Type:** application/x-www-form-urlencoded;charset=UTF-8

**Description:** a

**Request-example:**
```bash
curl -X GET -i 'http://127.0.0.1:3333/c/a'
```
**Response-fields:**

| Field | Type | Description | Since |
|-------|------|-------------|-------|
|success|boolean|is success|-|
|code|string|error code|-|
|message|string|error message|-|
|data|object|data|-|
|└─id|string|id|-|

**Response-example:**
```json
{
  "success": true,
  "code": "",
  "message": "",
  "data": {
    "id": ""
  }
}
```

### b
**URL:** http://127.0.0.1:3333/c/b

**Type:** GET

**Author:** test

**Content-Type:** application/x-www-form-urlencoded;charset=UTF-8

**Description:** b

**Request-example:**
```bash
curl -X GET -i 'http://127.0.0.1:3333/c/b'
```
**Response-fields:**

| Field | Type | Description | Since |
|-------|------|-------------|-------|
|success|boolean|is success|-|
|code|string|error code|-|
|message|string|error message|-|
|data|object|data|-|
|└─id|string|id|-|

**Response-example:**
```json
{
  "success": true,
  "code": "",
  "message": "",
  "data": {
    "id": ""
  }
}
```

### c
**URL:** http://127.0.0.1:3333/c/c

**Type:** GET

**Author:** test

**Content-Type:** application/x-www-form-urlencoded;charset=UTF-8

**Description:** c

**Request-example:**
```bash
curl -X GET -i 'http://127.0.0.1:3333/c/c'
```
**Response-fields:**

| Field | Type | Description | Since |
|-------|------|-------------|-------|
|success|boolean|is success|-|
|code|string|error code|-|
|message|string|error message|-|
|data|object|data|-|
|└─id|string|id|-|

**Response-example:**
```json
{
  "success": true,
  "code": "",
  "message": "",
  "data": {
    "id": ""
  }
}
```

**Comment by shalousun** [comment]
@UN010 Which version of Smart-Doc are you using? If it's an older version, I suggest upgrading to the latest one to see if that helps.
你使用的那个版本的smart-doc，如果版本低建议先升级到最新看下

**Comment by UN010** [comment]
@linwumingshi @shalousun 
感谢两位的解答
使用版本为3.0.2，mojo为rpc-html，解析RPC接口
根据我的问题编写了一个demo，源码暂时无法导出，现提供解析输出的html文件，demo结构可能略复杂，因为编写了很多场景，关键问题都是一个interface解析展示的方法列表，只有单层继承接口
其中Test1Service在继承关系上继承了其他所有接口，应该解析出四个方法
期待两位的答复
[接口文档.zip](https://github.com/TongchengOpenSource/smart-doc/files/14597983/default.zip)
