### ISSUE TITLE
Optimization of collection type parameters

### ISSUE THREAD

**Issue by JeenoD** [TongchengOpenSource/smart-doc#76]
smart-doc version: 2.0.1

## Optimization of Collection Type Parameters
When a custom object has a Set<Long> or Set<xxEnum> property, the type displayed in the generated HTML documentation is 'object'. This makes it impossible for the frontend to know what type of data to pass based on the documentation.

### Example Explanation
Custom classes: TeacherDO, StudentDO, SubjectEnum
In TeacherDO there is a Set<SubjectEnum> subjectSet; in the generated documentation, the type of subjectSet is shown as 'object';
In TeacherDO there is also a Set<StudentDO> studentSet; in the generated documentation, the type of studentSet is also shown as 'object', but it includes the associated field descriptions of StudentDO.
In these two cases, could the corresponding field types of Set be marked as Array? If it is an Enum type, could the optional values be listed as well?

### Motivation
To reduce communication issues between the frontend and backend caused by unclear documentation.

**Comment by shalousun** [comment]
@JeenoD The display of arrays can be addressed, but theoretically, it should not increase the frontend's burden because usage examples or response examples are very important. Experienced developers even prefer to view the JSON structure in examples.
Enumerations are quite troublesome; with many enumerations, the documentation looks very cluttered. For tools that we particularly care about aesthetically, this requires some thought.
