### ISSUE TITLE
When there is a "package-info.java" package description file in the project, running the Maven plugin will cause an error.

### ISSUE THREAD

**Issue by oiltea94** [TongchengOpenSource/smart-doc#780]
When there is a "package-info.java" package description file in the project, running the Maven plugin will report an error, but it does not affect the use result, and it is expected to skip.
当项目中存在“package-info.java”包描述文件时，运行maven插件会报错，但是不影响使用结果，期望能跳过

**Comment by shalousun** [comment]
@oiltea Next time when you submit an issue, please follow the community's issue template. The community has started some international promotion efforts, so please also help with the translation. The issue with the package-info.java error may be caused by incorrect content in the package-info.java file within the project.

下次提交问题时，请按照社区的问题模板来填写。社区已经开始了一些国际推广工作，所以也请麻烦帮忙做下翻译(社区贡献者最近花了很多时间去做很多issue的翻译工作，大家也非常不容易，因此麻烦理解下)。关于`package-info.java`错误的问题，可能是由于项目内的`package-info.java`文件中的内容不正确导致的

The `package-info.java` file must contain a valid package declaration, for example:
<img width="1020" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/9592228/cf537862-f3d3-42ce-b7e9-bfeff734efcc">

After testing, when the code in `package-info.java` is correct, smart-doc can execute normally.

**Comment by shalousun** [comment]
reference https://smart-doc-group.github.io/#/faq/faq?id=package-infojava-error
