### ISSUE TITLE
Can support to show field length in the document table

### ISSUE THREAD

**Issue by jay763190097** [TongchengOpenSource/smart-doc#900]
### Contact Details

jiangmang.1992@163.com

### Version

3.0.7

### Plugin

smart-doc-maven-plugin

### Build tool version

3.6.2

### Jdk version

17

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Same with title

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Same with title

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Same with title

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Same with title

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by shalousun** [comment]
@jay763190097 If you use JSR validation annotations on your fields, smart-doc can extract this validation information and display it in the documentation. This information will be appended to the field comments, for example, when using the `@Length` annotation, smart-doc will extract it.
```
public class Product {

    /**
     * Product id
     */
    private Long id;

    /**
     * Product name
     */
    @Length(max = 20, message = "Product name length must be less than 20")
    private String name;

    /**
     * Product price
     */
    private Double price;

    /**
     * Product picture url
     */
    private String pictureUrl;
}

```
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/6cd8a885-54d7-4a87-b078-d4fb0f8c220b">

Of course, since JSR includes many validation rules, the community does not design a separate column for each validation rule. Instead, the validation rules defined by developers are directly extracted and appended to the comments. If you do not want these validations to be displayed, you can set `showValidation` to `false` to disable it. You might want to review the official documentation for more details.

**Comment by jay763190097** [comment]
理解你的考虑点，但是length其实是很多标准文档需要的一列，我们可以增加一个配置是否需要显示这一列。

**Comment by shalousun** [comment]
> 理解你的考虑点，但是length其实是很多标准文档需要的一列，我们可以增加一个配置是否需要显示这一列。

Next time, if you need to write in Chinese, please use Qwen or other tools to translate it into English. The smart-doc community is currently a global open-source community, and we have invested a lot of effort into promoting it overseas. Community developers have also put in a great deal of work to do translations. Therefore, we appreciate understanding and respect for their efforts.

Adding extra columns is not within the community's consideration. Having a need for `length` would also imply needs for `max` and `min`, which could make the document layout design less desirable. The community aims to maintain the simplicity and cleanliness of the documentation layout.
